name: wongbryan
favicon: null
layout_spectrum: 0.49968
typography_spectrum: 0.88162
title: Bryan Wong Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e5e6'
    - '#c0bfbd'
    - '#10151b'
    - '#9b9693'
    - '#5b5b59'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
